[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM11
monitor_port = COM11
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  winlinvip/SimpleDHT
